package com.raghu.medical.model;
// Generated Nov 24, 2016 6:48:19 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice")
public class Invoice extends BaseEntity<Long> implements java.io.Serializable {

    private Set<CustomerPurchase> customerPurchases;

    public Invoice() {
    }

    public Invoice(Set<CustomerPurchase> customerPurchases) {
        this.customerPurchases = customerPurchases;
    }

    public Invoice(Set<CustomerPurchase> customerPurchases, Long lastModifiedBy, Date lastModifiedDate, Long createdBy,
                   Date createdDate) {
        this.customerPurchases = customerPurchases;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy="invoice")
    public Set<CustomerPurchase> getCustomerPurchases() {
		return customerPurchases;
	}

	public void setCustomerPurchases(Set<CustomerPurchase> customerPurchases) {
		this.customerPurchases = customerPurchases;
	}

	
    
    

}
