package com.raghu.medical.model;
// Generated Nov 23, 2016 7:14:15 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MedicineType generated by hbm2java
 */
@Entity
@Table(name = "medicine_type", catalog = "mms")
public class MedicineType extends BaseEntity<Long> implements java.io.Serializable {

    private String medicineType;

    private Set<Medicine> medicines = new HashSet<Medicine>(0);

    public MedicineType() {
    }

    public MedicineType(String medicineType) {
        this.medicineType = medicineType;
    }

    public MedicineType(String medicineType, Long lastModifiedBy, Date lastModifiedDate, Long createdBy,
                        Date createdDate, Set<Medicine> medicines) {
        this.medicineType = medicineType;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.medicines = medicines;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }


    @Column(name = "MEDICINE_TYPE", nullable = false, length = 50)
    public String getMedicineType() {
        return this.medicineType;
    }

    public void setMedicineType(String medicineType) {
        this.medicineType = medicineType;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "medicineType")
    public Set<Medicine> getMedicines() {
        return this.medicines;
    }

    public void setMedicines(Set<Medicine> medicines) {
        this.medicines = medicines;
    }

}
