package com.raghu.model;
// Generated 3 Mar, 2018 4:03:03 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MedicinePurchase generated by hbm2java
 */
@Entity
@Table(name = "medicine_purchase", uniqueConstraints = { @UniqueConstraint(columnNames = "MEDICINE_ID"),
		@UniqueConstraint(columnNames = "INVOICE_ID") })
public class MedicinePurchase implements java.io.Serializable {

	private Long id;
	private Invoice invoice;
	private Medicine medicine;
	private BigDecimal price;
	private BigDecimal discount;
	private Integer quantity;
	private Long lastModifiedBy;
	private Date lastModifiedDate;
	private Long createdBy;
	private Date createdDate;
	private Date deleteDate;

	public MedicinePurchase() {
	}

	public MedicinePurchase(Invoice invoice, Medicine medicine, BigDecimal price) {
		this.invoice = invoice;
		this.medicine = medicine;
		this.price = price;
	}

	public MedicinePurchase(Invoice invoice, Medicine medicine, BigDecimal price, BigDecimal discount, Integer quantity,
			Long lastModifiedBy, Date lastModifiedDate, Long createdBy, Date createdDate, Date deleteDate) {
		this.invoice = invoice;
		this.medicine = medicine;
		this.price = price;
		this.discount = discount;
		this.quantity = quantity;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.deleteDate = deleteDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVOICE_ID", unique = true, nullable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICINE_ID", unique = true, nullable = false)
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@Column(name = "PRICE", nullable = false, precision = 11, scale = 5)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "DISCOUNT", precision = 11, scale = 5)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "QUANTITY")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "LAST_MODIFIED_BY")
	public Long getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Long lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETE_DATE", length = 19)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

}
